### ISSUE TITLE
Ipad integration with external keyboard is still broken

### ISSUE THREAD

**Issue by ildodo12** [overleaf/web#611]
Issues #13 and #312 are now closed, and I cannot really understand why. The two problems persist and make sharelatex unusable in those cases. Please, please, address this issue.

**Comment by egrefen** [comment]
Having the same problem with iPad Pro (2017) and smart keyboard cover, with iOS 11. Would be great to have a fix.

**Comment by pbruneau** [comment]
Hacking around I found out that the problem comes from ace editor (web-sharelatex/public/js/ace-1.2.5). The problem with iPad+keyboard is known by ace devs (https://github.com/ajaxorg/ace/issues/3157), and has been solved in their 1.2.7 release.

As I’m installing the full sharelatex system using docker-compose, I hacked around this way:
- download of adequate ace build 1.2.9 (https://github.com/ajaxorg/ace-builds/tree/master/src-noconflict)
- in the sharelatex docker image, replace the version in /var/www/sharelatex/web/public/js/ace-1.2.5 with the former (replace 1.2.9 by 1.2.5 in the source)
- run “grunt requirejs” when in the web folder

I know this is a quick-and-dirty fix, but then it works :) As for integrating in the web-sharelatex repo, I’ll leave that to someone more knowledgeable in terms of integration and testing :)

**Comment by hugolundin** [comment]
Any updates on this one? Do you know @pbruneau why they have not updated to a newer version of ace?

**Comment by zteitler** [comment]
Bump (still a problem in September 2018)

**Comment by jdleesmiller** [comment]
The ace upgrade was released recently. It won't fix all iPad issues, but it should help with this one.

**Comment by hugolundin** [comment]
Thank you!
