### ISSUE TITLE
\bibliography{\jobname} is not support

### ISSUE THREAD

**Issue by bersbersbers** [overleaf/web#620]
If you use some project.tex alongside project.bib, a local installation will support \bibliography{\jobname} just fine. ShareLaTeX doesn't, claiming many undefined references as if project.bib did not exist or was empty.

**Comment by Joehein** [comment]
This is because in sharelatex \jobname always evaluates to output. You can rename project.bib to output.bib and it should work. 
A more sophisticated solution would be to use .latexmkrc to make a symlink output.bib->project.bib. But this depends on the installation of sharelatex, the global configuration of latexmk, if you want to have this globally (workstation) or locally (user) or projectwise (project folder). Since the latexmkrc file is a Perl script invoked by latexmk (the scheduler for a recompile) at every recompile, one can do everything there.....

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
