### ISSUE TITLE
Review Tab / Comments System

### ISSUE THREAD

**Issue by joobei** [overleaf/web#651]
I'm curious why the "review" feature (available in the online overleaf sharelatex images) is not available on this image. If this is a motivation to use the paid services then fair enough. I would just prefer to see it documented somewhere. I cannot find any info on this.

**Comment by igoralmeida** [comment]
Just installed the docker version and it seems this is still the case.

**Comment by zeigerpuppy** [comment]
My understanding is that the core team is not interested in open sourcing the comment system.  However, I think it would not be too difficult to implement a simple commenting system based upon data stored in the LaTeX file and then rendered in a modified chat viewer.

We'd probably have to maintain a fork, but there's not much upstream activity since the product went commercial, so it's probably worth forking anyway.

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
